### ISSUE TITLE
NUM_STEPS or NUM_EPISODES?

### ISSUE THREAD

**Issue by chao1224** [MarcusOlivecrona/REINVENT#1]
Just want to confirm one thing.

So in this [line](https://github.com/MarcusOlivecrona/REINVENT/blob/master/model.py#L270), should this `self.NUM_STEPS` be the number of episodes in the context of RL?

Appreciate any help.

**Comment by MarcusOlivecrona** [comment]
Hi,

In every training step, batch_size episodes are sampled as a batch. Therefor, the total number of episodes sampled would be batch_size * num_steps.

Marcus
