### ISSUE TITLE
where to get the mols.smi file ? 

### ISSUE THREAD

**Issue by bigpeter88** [MarcusOlivecrona/REINVENT#11]
Hi, may I know where I can get the mols.smi file as the data source to filter the smiles? 
I just cannot find it in this Github site. 

thx a lot! 
Peter

**Comment by anny0316** [comment]
I have the problem， too

**Comment by alfa0112** [comment]
Hi,
"data" directory already has the "Voc" and "mols_filtered.smi" built from filtered SMILES from ChEMBLE database.
Moreover, there is the trained "Prior.ckpt" in the same directory.
If you don't want to restructure the Prior file, you can use this.
Or not, you can make "mols.smi" that is a text file that contains SMILES to train Prior.

If you want to get the original"mols.smi", the following page may show more information.
(Sorry, I did not verify the contents of the .tar.gz file.)
https://github.com/MarcusOlivecrona/REINVENT/releases/tag/v1.0.1

**Comment by MarcusOlivecrona** [comment]
Hi,

The `mols.smi` is generic, but if you want to use the same dataset as in the article it is called `prior_trainingset` and can be found in the `data.tar.gz` file available under Releases > 1.0.1.
