### ISSUE TITLE
Size mismatch in MultiGRU

### ISSUE THREAD

**Issue by meghanakaranam1** [MarcusOlivecrona/REINVENT#14]
I am getting this issue when I run the command : **!python main.py --scoring-function activity_model --num-steps 1000**
Can anyone help me solve this issue please? @MarcusOlivecrona @tblaschke

![image](https://user-images.githubusercontent.com/81307675/226085088-6aa89b9b-586b-460e-b6e4-1cc304c42dcd.png)

**Comment by MarcusOlivecrona** [comment]
Hi!

This issue seems to be because the MultiGRU architecture has changed with newer PyTorch versions. See https://github.com/Mishima-syk/13/issues/1

Try to revert to version `0.3` as mentioned in that issue.

**Comment by meghanakaranam1** [comment]
> Hi!
> 
> This issue seems to be because the MultiGRU architecture has changed with newer PyTorch versions. See [Mishima-syk/13#1](https://github.com/Mishima-syk/13/issues/1)
> 
> Try to revert to version `0.3` as mentioned in that issue.

I tried reverting back to version 0.3 in google colab. But it didnt work, 
I tried using  pip and wheel. It is showing error for both. 
can you please help me?
![image](https://user-images.githubusercontent.com/81307675/227700639-ed38e08a-cc1a-409d-8edd-d51ad732e97c.png)
