### ISSUE TITLE
Inquiry regarding logging of weights

### ISSUE THREAD

**Issue by meghanakaranam1** [MarcusOlivecrona/REINVENT#16]
can you please let me know why are the weights being logged here? How is it helping in training the data?
@MarcusOlivecrona @tblaschke

![image](https://github.com/MarcusOlivecrona/REINVENT/assets/81307675/80266dd5-8921-416e-a15b-c3ed01b11483)

**Comment by MarcusOlivecrona** [comment]
Looking at the parameters during training provides an easy way to debug issues and monitor training progression.
