### ISSUE TITLE
Issue in the output

### ISSUE THREAD

**Issue by meghanakaranam1** [MarcusOlivecrona/REINVENT#17]
hello, 
I gave mols.smi containing 78 smiles of target BRAF kinase. In return, generated small molecules. Can you please let me know how to solve this issue? Is there a solution to it? @MarcusOlivecrona 
Attaching mols.smi  and output of the REINVENT model for your reference 
[mols.txt](https://github.com/MarcusOlivecrona/REINVENT/files/11610210/mols.txt)
![image](https://github.com/MarcusOlivecrona/REINVENT/assets/81307675/fcf63370-4f0b-4b55-b745-c72d60779971)

**Comment by MarcusOlivecrona** [comment]
78 structures is a much smaller dataset than the standard provided. The
prior model should have no problems learning to generate these, although it
may struggle to generate new structures. Make sure that proper structures
are being generated when training the prior, and then have a look at what
is happening during the training of the agent.
