### ISSUE TITLE
Where are the generated DRD2 molecules?

### ISSUE THREAD

**Issue by mostafachatillon** [MarcusOlivecrona/REINVENT#2]
I don't find the generated sample molecules in the DRD2 case. Are they in your release?

**Comment by MarcusOlivecrona** [comment]
Hi,

No, the molecules generated by the model are only shown partially in the pictures. But including them would probably have been a good idea! Are you still interested in them?

Marcus

**Comment by mostafachatillon** [comment]
No, thanks, I finished my paper.
