### ISSUE TITLE
an error when run test with main.py 

### ISSUE THREAD

**Issue by ybwu01** [MarcusOlivecrona/REINVENT#4]
Hi, 

Thanks for sharing the code. I just tried to run a test with the command:
main.py --scoring-function activity_model --num-steps 1000

However, an error appeared:

Traceback (most recent call last):
  File "~/main.py", line 59, in <module>
    train_agent(**arg_dict)
  File "~/train_agent.py", line 38, in train_agent
    Prior.rnn.load_state_dict(torch.load('data/Prior.ckpt'))
  File "~/software/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named embedding.weight, whose dimensions in the model are torch.Size([11, 128]) and whose dimensions in the checkpoint are torch.Size([50, 128]).

Thanks,

Yibing

**Comment by lmpan** [comment]
Hi Thomas,

Thank you for the reply! Downgrade pytorch to 0.3.1, and it works. Thank you for sharing this great work.

Regards,
LP

**Comment by ybwu01** [comment]
Thanks Thomas and LP. I will try to use the old version (pytorch 0.3).
Yibing

**Comment by MarcusOlivecrona** [comment]
Thanks Thomas!
